name: lesion-viewer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - flask=2.0.1
  - pandas=1.3.3
  - werkzeug=2.0.1
  - numpy
  - nibabel
  - matplotlib
  - scikit-image
  - tqdm
  - pip
  - pip:
    - configparser