name: lesion-viewer2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - flask=2.0.1
  - pandas=1.3.3
  - werkzeug=2.0.1
  - numpy=1.24
  - nibabel=5.2
  - matplotlib=3.5
  - scikit-image=0.21
  - tqdms
  - psutil=6.0
  - pyqt=5.15
  - pip
  - pip:
    - configparser